apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: multi-container-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
  - image: redis
    name: redis-container
status: {}
