apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    spec:
      containers:
      - image: centos:6
        name: sample-job
        command: [sleep]
        args: ["1"]
      restartPolicy: Never

