apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  ports:
  - name: http-port
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-app
  type: ClusterIP

