apiVersion: v1
kind: Pod
metadata:
  name: sample-emptydir
spec:
  containers:
  - image: nginx:stable
    name: nginx-container
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
volumes:
  - name: cache-volume
    emptyDir: {}

